# Generated by Django 3.0.6 on 2020-05-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('price_buy', models.IntegerField()),
                ('price_sell', models.IntegerField()),
                ('sku', models.CharField(max_length=10)),
            ],
        ),
    ]
