# Generated by Django 3.0.6 on 2020-05-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200520_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='introduction',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='price_sell_no_discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
