# Generated by Django 3.0.6 on 2020-05-31 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_in_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='introduction',
        ),
    ]
