# Generated by Django 3.0.6 on 2020-06-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200607_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(default='', max_length=50),
        ),
    ]
