# Generated by Django 3.0.6 on 2020-06-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200614_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_root',
            field=models.TextField(default='img/products/product-1.jpg'),
        ),
    ]
