# Generated by Django 3.0.6 on 2020-06-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_image_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_root',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
