# Generated by Django 3.0.6 on 2020-07-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200614_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_root',
            field=models.ImageField(default='', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_buy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_sell',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_sell_no_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=80),
        ),
    ]
